// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c4FCQiVEmUqfPef3MjSmg8
// Component: SDagfCRh-2CQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsqExrow76Zrl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: QExrow-76Zrl/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: c4FCQiVEmUqfPef3MjSmg8/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: SDagfCRh-2CQ/css

import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: YmZHPP8Bqtaf/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  landingPage?: Flex__<"div">;
  section?: Flex__<"section">;
  navigationBar?: Flex__<typeof NavigationBar>;
  heading?: Flex__<"div">;
  heading4?: Flex__<"div">;
  hero?: Flex__<typeof PlasmicImg__>;
  heading3?: Flex__<"div">;
  container?: Flex__<"div">;
  apriwa?: Flex__<"a"> & Partial<LinkProps>;
  asc?: Flex__<"a"> & Partial<LinkProps>;
  citadel?: Flex__<"a"> & Partial<LinkProps>;
  enginePlus?: Flex__<"a"> & Partial<LinkProps>;
  jvs?: Flex__<"a"> & Partial<LinkProps>;
  porsche?: Flex__<"a"> & Partial<LinkProps>;
  rizqyMotorsport?: Flex__<"a"> & Partial<LinkProps>;
  semenMerahPutih?: Flex__<"a"> & Partial<LinkProps>;
  siloMaritime?: Flex__<"a"> & Partial<LinkProps>;
  heading5?: Flex__<"div">;
  sliderCarousel2?: Flex__<typeof SliderWrapper>;
  footer2?: Flex__<"div">;
  logo2?: Flex__<"div">;
  social7?: Flex__<"div">;
  social5?: Flex__<"div">;
  social6?: Flex__<"div">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    query: usePlasmicDataOp(() => {
      return {
        sourceId: "eA7ZA8G1r1sNAkLZ6fF4gN",
        opId: "dd53357a-e00e-4feb-963c-ea28429b31e8",
        userArgs: {},
        cacheKey: `plasmic.$.dd53357a-e00e-4feb-963c-ea28429b31e8.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqExrow76Zrl()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"landingPage"}
          data-plasmic-override={overrides.landingPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.landingPage
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__ugMcO
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5Sik0)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: "/plasmic/carsandclo/images/cncXPscIsvg.svg",
                      fullWidth: 449.49,
                      fullHeight: 98.63,
                      aspectRatio: 4.557335
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yh6Fr)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__yNWnR
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__h3JzT
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__omr0V
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__i4GIy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/menu.svg"}
                />
              }
              responsiveBreakpoint={768}
            />

            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1Bk7D)}
            >
              <div
                data-plasmic-name={"heading"}
                data-plasmic-override={overrides.heading}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.heading
                )}
              >
                {"CARS AND CLO X PORSCHE SPRINT CHALLENGE INDONESIA'S"}
              </div>
              <div
                data-plasmic-name={"heading4"}
                data-plasmic-override={overrides.heading4}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.heading4
                )}
              >
                {"GET READY TO REV UP YOUR STYLE"}
              </div>
            </Stack__>
            <PlasmicImg__
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              alt={""}
              className={classNames(sty.hero)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "800px"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "100%"
                  : "100%"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/carsandclo/images/mainpng.png",
                fullWidth: 1200,
                fullHeight: 800,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"heading3"}
              data-plasmic-override={overrides.heading3}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heading3
              )}
            >
              {"ALL COLLECTIONS"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <PlasmicLink__
                data-plasmic-name={"apriwa"}
                data-plasmic-override={overrides.apriwa}
                className={classNames(projectcss.all, projectcss.a, sty.apriwa)}
                component={Link}
                href={`/${"apriwa"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6Pbwl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g74J
                    )}
                  >
                    {"Apriwa\nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ad4B5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ztio2
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__pzbGr)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fJzD6)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/apriwa2Xpng2.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"asc"}
                data-plasmic-override={overrides.asc}
                className={classNames(projectcss.all, projectcss.a, sty.asc)}
                component={Link}
                href={`/${"asc"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iRRoD)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xCnpo
                    )}
                  >
                    {"ASC\nMonster"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nlsgv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8WXHq
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__uaRbc)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5X3V4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/asc2X2Xpng2.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"citadel"}
                data-plasmic-override={overrides.citadel}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.citadel
                )}
                component={Link}
                href={`/${"citadel"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yaHgl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lbdIp
                    )}
                  >
                    {"Citadel \nRacing Team"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jQzzP)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ydcdg
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__jDDg)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tLfKi)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/citadel2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"enginePlus"}
                data-plasmic-override={overrides.enginePlus}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.enginePlus
                )}
                component={Link}
                href={`/${"engineplus"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__o6HuT)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gxmbg
                    )}
                  >
                    {"Engine Plus \nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___564Ls)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xZgF
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__goR9K)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bud4E)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/enginePlus2X2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"jvs"}
                data-plasmic-override={overrides.jvs}
                className={classNames(projectcss.all, projectcss.a, sty.jvs)}
                component={Link}
                href={`/${"jvs"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__mi6Lc)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pMtFg
                    )}
                  >
                    {"JVS MS Glow\nRacing"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fWYwL)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1Jwcx
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__qzBo)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__prFrd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/jvs2X1Png.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"porsche"}
                data-plasmic-override={overrides.porsche}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.porsche
                )}
                component={Link}
                href={`/${"porsche"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ynkes)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__waQOf
                    )}
                  >
                    {"Porsche\nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nmk3R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7IuCi
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__lUuSf)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jpCLs)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/baseBlue2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"rizqyMotorsport"}
                data-plasmic-override={overrides.rizqyMotorsport}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.rizqyMotorsport
                )}
                component={Link}
                href={`/${"rizqy"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hC2Bz)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__npVUo
                    )}
                  >
                    {"Rizqy \nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zZld2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fa31T
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__i38E8)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__icsh)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/rizqyMotorsport2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"semenMerahPutih"}
                data-plasmic-override={overrides.semenMerahPutih}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.semenMerahPutih
                )}
                component={Link}
                href={`/${"smp"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4OyYv)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kqgdo
                    )}
                  >
                    {"Merah Putih \nRacing"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__sTzDv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vfKqb
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__oxkNy)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kv8Y2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/semenMerahPutih2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"siloMaritime"}
                data-plasmic-override={overrides.siloMaritime}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.siloMaritime
                )}
                component={Link}
                href={`/${"silo"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8SuB)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lsnF
                    )}
                  >
                    {"Sillo Maritime\nPerdana 78 Racing"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__krpRa)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ollRf
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__mPKvO)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fr51O)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/btpn2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
            </Stack__>
            <div
              data-plasmic-name={"heading5"}
              data-plasmic-override={overrides.heading5}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heading5
              )}
            >
              {"ALL COLLECTIONS"}
            </div>
            {(() => {
              const child$Props = {
                arrows: false,
                autoplay: false,
                autoplaySpeed: 0,
                beforeChange: generateStateOnChangePropForCodeComponents(
                  $state,
                  "currentSlide",
                  ["sliderCarousel2", "currentSlide"],
                  SliderWrapper_Helpers
                ),
                centerMode: true,
                className: classNames("__wab_instance", sty.sliderCarousel2),
                cssEase: "linear",
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel2",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel2"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel2__slider"],
                speed: 5000
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel2.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel2"}
                  data-plasmic-override={overrides.sliderCarousel2}
                  {...child$Props}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vjLi)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tCoei)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/carsandclo/images/_2Png2.png",
                        fullWidth: 1200,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sEp04)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__dNfio)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/carsandclo/images/_3Png2.png",
                        fullWidth: 1200,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iC7Xn)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yecbv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/carsandclo/images/_8Png.png",
                        fullWidth: 1200,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </SliderWrapper>
              );
            })()}
          </section>
          <Stack__
            as={"div"}
            data-plasmic-name={"footer2"}
            data-plasmic-override={overrides.footer2}
            hasGap={true}
            className={classNames(projectcss.all, sty.footer2)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__cMaJn
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xkKhy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"178px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/cncXPsci1Invertedsvg.svg",
                    fullWidth: 178,
                    fullHeight: 40,
                    aspectRatio: 4.45
                  }}
                />
              </PlasmicLink__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zmNi5
                )}
              >
                {"Official Apparels Partner"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"social7"}
              data-plasmic-override={overrides.social7}
              hasGap={true}
              className={classNames(projectcss.all, sty.social7)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x6J14
                )}
              >
                {"Connect with Cars and Clo"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zot8Y)}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__gfxMr
                  )}
                  component={Link}
                  href={"https://www.instagram.com/carsandclo/"}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__aupa2)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/carsandclo/images/instagramsvg.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__estDq
                  )}
                  component={Link}
                  href={
                    "https://www.tiktok.com/@carsandclo?_t=8nQ5PnLKxmq&_r=1"
                  }
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__u0U0L)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/carsandclo/images/tiktoksvg.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </PlasmicLink__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"social5"}
              data-plasmic-override={overrides.social5}
              hasGap={true}
              className={classNames(projectcss.all, sty.social5)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vF6Su
                )}
              >
                {"Marketplace"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xKlQn)}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__rsy93
                  )}
                  component={Link}
                  href={"https://shopee.co.id/carsandcloofficial"}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__lvkSo)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/carsandclo/images/shopeesvg.svg",
                      fullWidth: 84,
                      fullHeight: 32,
                      aspectRatio: 2.625
                    }}
                  />
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__bs9S
                  )}
                  component={Link}
                  href={"https://www.tokopedia.com/carsandcloofficial"}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__t3QYh)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/carsandclo/images/tokpedsvg.svg",
                      fullWidth: 99,
                      fullHeight: 32,
                      aspectRatio: 3.09375
                    }}
                  />
                </PlasmicLink__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wx7E)}
                  displayHeight={"32px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/tShopsvg.svg",
                    fullWidth: 114,
                    fullHeight: 32,
                    aspectRatio: 3.5625
                  }}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__pR7C)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lb6V3)}
                  displayHeight={"32px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/carsandclo/images/bigcartesvg2.svg",
                    fullWidth: 89,
                    fullHeight: 32,
                    aspectRatio: 2.78125
                  }}
                />
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"social6"}
              data-plasmic-override={overrides.social6}
              hasGap={true}
              className={classNames(projectcss.all, sty.social6)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bXwdz
                )}
              >
                {"Want to collaborate?"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__u4QH)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___89Dc
                  )}
                  component={Link}
                  href={"mailto:cloandcars@gmail.com"}
                  platform={"nextjs"}
                >
                  {"Get in touch with us"}
                </PlasmicLink__>
              </div>
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pEr66
              )}
            >
              {"\u00a9 2024 Cars and Clo"}
            </div>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  landingPage: [
    "landingPage",
    "section",
    "navigationBar",
    "heading",
    "heading4",
    "hero",
    "heading3",
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime",
    "heading5",
    "sliderCarousel2",
    "footer2",
    "logo2",
    "social7",
    "social5",
    "social6"
  ],
  section: [
    "section",
    "navigationBar",
    "heading",
    "heading4",
    "hero",
    "heading3",
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime",
    "heading5",
    "sliderCarousel2"
  ],
  navigationBar: ["navigationBar"],
  heading: ["heading"],
  heading4: ["heading4"],
  hero: ["hero"],
  heading3: ["heading3"],
  container: [
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime"
  ],
  apriwa: ["apriwa"],
  asc: ["asc"],
  citadel: ["citadel"],
  enginePlus: ["enginePlus"],
  jvs: ["jvs"],
  porsche: ["porsche"],
  rizqyMotorsport: ["rizqyMotorsport"],
  semenMerahPutih: ["semenMerahPutih"],
  siloMaritime: ["siloMaritime"],
  heading5: ["heading5"],
  sliderCarousel2: ["sliderCarousel2"],
  footer2: ["footer2", "logo2", "social7", "social5", "social6"],
  logo2: ["logo2"],
  social7: ["social7"],
  social5: ["social5"],
  social6: ["social6"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  landingPage: "div";
  section: "section";
  navigationBar: typeof NavigationBar;
  heading: "div";
  heading4: "div";
  hero: typeof PlasmicImg__;
  heading3: "div";
  container: "div";
  apriwa: "a";
  asc: "a";
  citadel: "a";
  enginePlus: "a";
  jvs: "a";
  porsche: "a";
  rizqyMotorsport: "a";
  semenMerahPutih: "a";
  siloMaritime: "a";
  heading5: "div";
  sliderCarousel2: typeof SliderWrapper;
  footer2: "div";
  logo2: "div";
  social7: "div";
  social5: "div";
  social6: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "landingPage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("landingPage"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    navigationBar: makeNodeComponent("navigationBar"),
    heading: makeNodeComponent("heading"),
    heading4: makeNodeComponent("heading4"),
    hero: makeNodeComponent("hero"),
    heading3: makeNodeComponent("heading3"),
    container: makeNodeComponent("container"),
    apriwa: makeNodeComponent("apriwa"),
    asc: makeNodeComponent("asc"),
    citadel: makeNodeComponent("citadel"),
    enginePlus: makeNodeComponent("enginePlus"),
    jvs: makeNodeComponent("jvs"),
    porsche: makeNodeComponent("porsche"),
    rizqyMotorsport: makeNodeComponent("rizqyMotorsport"),
    semenMerahPutih: makeNodeComponent("semenMerahPutih"),
    siloMaritime: makeNodeComponent("siloMaritime"),
    heading5: makeNodeComponent("heading5"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    footer2: makeNodeComponent("footer2"),
    logo2: makeNodeComponent("logo2"),
    social7: makeNodeComponent("social7"),
    social5: makeNodeComponent("social5"),
    social6: makeNodeComponent("social6"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
