// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c4FCQiVEmUqfPef3MjSmg8
// Component: LBDmPWl-ib2_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: c4FCQiVEmUqfPef3MjSmg8/projectcss
import sty from "./PlasmicSizeChart.module.css"; // plasmic-import: LBDmPWl-ib2_/css

createPlasmicElementProxy;

export type PlasmicSizeChart__VariantMembers = {};
export type PlasmicSizeChart__VariantsArgs = {};
type VariantPropType = keyof PlasmicSizeChart__VariantsArgs;
export const PlasmicSizeChart__VariantProps = new Array<VariantPropType>();

export type PlasmicSizeChart__ArgsType = {};
type ArgPropType = keyof PlasmicSizeChart__ArgsType;
export const PlasmicSizeChart__ArgProps = new Array<ArgPropType>();

export type PlasmicSizeChart__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultSizeChartProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSizeChart__RenderFunc(props: {
  variants: PlasmicSizeChart__VariantsArgs;
  args: PlasmicSizeChart__ArgsType;
  overrides: PlasmicSizeChart__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__xH9T0
        )}
        id={"lblname"}
      >
        {"Oversized T-Shirt Size Chart"}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__qX5Fh)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__shh4J
          )}
          id={"lblsize"}
        >
          {"Size"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___0NyU
          )}
          id={"lblsize"}
        >
          {"Height"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___66B7I
          )}
          id={"lblsize"}
        >
          {"Width"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___6W8Lv)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__uOxRv
          )}
          id={"lblsize"}
        >
          {"S"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__jlWji
          )}
          id={"lblsize"}
        >
          {"64"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__aewZf
          )}
          id={"lblsize"}
        >
          {"54"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___8UlX)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___7XOGk
          )}
          id={"lblsize"}
        >
          {"M"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ph3Gc
          )}
          id={"lblsize"}
        >
          {"68"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___5Y9Fa
          )}
          id={"lblsize"}
        >
          {"58"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__qNTpn)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__vgJk0
          )}
          id={"lblsize"}
        >
          {"L"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kHoM
          )}
          id={"lblsize"}
        >
          {"72"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ng8P1
          )}
          id={"lblsize"}
        >
          {"62"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__zCaB9)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__sWfhc
          )}
          id={"lblsize"}
        >
          {"XL"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oAus8
          )}
          id={"lblsize"}
        >
          {"75"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___0VTSl
          )}
          id={"lblsize"}
        >
          {"62"}
        </div>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__hEoiw
        )}
        id={"lblname"}
      >
        {"*Measurement in centimeters"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSizeChart__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSizeChart__VariantsArgs;
    args?: PlasmicSizeChart__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSizeChart__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSizeChart__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSizeChart__ArgProps,
          internalVariantPropNames: PlasmicSizeChart__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSizeChart__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSizeChart";
  } else {
    func.displayName = `PlasmicSizeChart.${nodeName}`;
  }
  return func;
}

export const PlasmicSizeChart = Object.assign(
  // Top-level PlasmicSizeChart renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSizeChart
    internalVariantProps: PlasmicSizeChart__VariantProps,
    internalArgProps: PlasmicSizeChart__ArgProps
  }
);

export default PlasmicSizeChart;
/* prettier-ignore-end */
