// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c4FCQiVEmUqfPef3MjSmg8
// Component: A_9WkEXTeBXf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: c4FCQiVEmUqfPef3MjSmg8/projectcss
import sty from "./PlasmicSizeChartSweater.module.css"; // plasmic-import: A_9WkEXTeBXf/css

createPlasmicElementProxy;

export type PlasmicSizeChartSweater__VariantMembers = {};
export type PlasmicSizeChartSweater__VariantsArgs = {};
type VariantPropType = keyof PlasmicSizeChartSweater__VariantsArgs;
export const PlasmicSizeChartSweater__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSizeChartSweater__ArgsType = {};
type ArgPropType = keyof PlasmicSizeChartSweater__ArgsType;
export const PlasmicSizeChartSweater__ArgProps = new Array<ArgPropType>();

export type PlasmicSizeChartSweater__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultSizeChartSweaterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSizeChartSweater__RenderFunc(props: {
  variants: PlasmicSizeChartSweater__VariantsArgs;
  args: PlasmicSizeChartSweater__ArgsType;
  overrides: PlasmicSizeChartSweater__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__zNeXf
        )}
        id={"lblname"}
      >
        {"Sweatshirt Size Chart"}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__cyTI)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__e6Xqj
          )}
          id={"lblsize"}
        >
          {"Size"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__nuYo
          )}
          id={"lblsize"}
        >
          {"Height"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__s21Aj
          )}
          id={"lblsize"}
        >
          {"Width"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__l7JVq)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oUqGu
          )}
          id={"lblsize"}
        >
          {"S"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kGbVx
          )}
          id={"lblsize"}
        >
          {"65"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__foc7Q
          )}
          id={"lblsize"}
        >
          {"52"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__jHlkc)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__aGwPp
          )}
          id={"lblsize"}
        >
          {"M"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__nyR3A
          )}
          id={"lblsize"}
        >
          {"67"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__nmK0J
          )}
          id={"lblsize"}
        >
          {"53"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__bqMb)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___6RvMa
          )}
          id={"lblsize"}
        >
          {"L"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bRzD
          )}
          id={"lblsize"}
        >
          {"70"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kuGMh
          )}
          id={"lblsize"}
        >
          {"56"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__eWt9W)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___9Ldq3
          )}
          id={"lblsize"}
        >
          {"XL"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ooWv7
          )}
          id={"lblsize"}
        >
          {"73"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___707VU
          )}
          id={"lblsize"}
        >
          {"61"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__i9ItU)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___3Bd9
          )}
          id={"lblsize"}
        >
          {"XXL"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bee7F
          )}
          id={"lblsize"}
        >
          {"76"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kqTb
          )}
          id={"lblsize"}
        >
          {"64"}
        </div>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__c1Cvu
        )}
        id={"lblname"}
      >
        {"*Measurement in centimeters"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSizeChartSweater__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSizeChartSweater__VariantsArgs;
    args?: PlasmicSizeChartSweater__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSizeChartSweater__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSizeChartSweater__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSizeChartSweater__ArgProps,
          internalVariantPropNames: PlasmicSizeChartSweater__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSizeChartSweater__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSizeChartSweater";
  } else {
    func.displayName = `PlasmicSizeChartSweater.${nodeName}`;
  }
  return func;
}

export const PlasmicSizeChartSweater = Object.assign(
  // Top-level PlasmicSizeChartSweater renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSizeChartSweater
    internalVariantProps: PlasmicSizeChartSweater__VariantProps,
    internalArgProps: PlasmicSizeChartSweater__ArgProps
  }
);

export default PlasmicSizeChartSweater;
/* prettier-ignore-end */
